# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker: # run the steps with Docker
      - image: circleci/node:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to Docker
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build Docker Image
          command: >
            docker build
            --build-arg NODE_ENV="production"
            --build-arg PORT="$PORT"
            --build-arg HOST="$HOST"
            -t brushblaster/commingsoon:v0.0.1 .
      - run:
          name: Run Docker Image
          command: docker run -d -p 127.0.0.1:80:3000 brushblaster/commingsoon:v0.0.1
      - run:
          name: Define script rights
          command: chmod u+x ./docker_push.sh
      - run:
          name: Deploy to Docker
          command: ./docker_push.sh
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
